name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.9]

    steps:

      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Code Climate tools
        if: matrix.python == 3.9
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage   
      - name: Run tests
        run: python -m unittest discover

      - name: Send test report to Code Climate
        if: matrix.python == 3.9 && success()
        env:
          CC_TEST_REPORTER_ID: 19953541bc706c78513ce47630980d1fc808417762acd0d9b2b376f12331071d
        run: |
          poetry run coverage xml
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build